/**
 * C4-PlantUML string helpers.
 *
 * There are two independent escaping layers:
 *  - PlantUML string literal syntax (`"`, `\`, control chars).
 *  - PlantUML Creole markup inside rendered text. In particular, `//`
 *    starts italic markup, so raw URLs such as `https://...` render as
 *    broken `[https: ...]</size>//` labels unless the slash pair is
 *    escaped with `~`.
 */

const escapeCreoleText = (value: string): string =>
  value.replaceAll("//", "~//");

/** Quote a string argument that C4-PlantUML renders as visible text. */
export const quotePlantumlText = (value: string): string =>
  JSON.stringify(escapeCreoleText(value));

/** Quote a string argument used as metadata, e.g. `$link` target. */
export const quotePlantumlArg = (value: string): string =>
  JSON.stringify(value);

/** Decode the Creole escape generated by `quotePlantumlText`. */
export const unescapePlantumlText = (value: string): string =>
  value.replaceAll("~//", "//");
