/**
 * Generate the reference docs from aact's own registries.
 *
 * Run via `pnpm docs:gen`. CI verifies the checked-in pages are
 * up-to-date with `git diff --exit-code docs/reference/` after running
 * the generator (`pnpm docs:check`), so the reference can never drift
 * from the rule registry, the citty command tree, or the format
 * registry.
 *
 * The generator owns the canonical formatting — `docs/reference/` is in
 * `.prettierignore` so prettier doesn't reflow it into a diff on every
 * `docs:check` run (same arrangement as `schemas/`).
 *
 * Runtime objects are loaded through jiti so this script can read the
 * live registries without a build step; type stripping handles the
 * script itself. `src/cli/index.ts` is NOT imported — it calls
 * `runMain` on load; the individual command objects are imported instead.
 */

import { mkdirSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import path from "node:path";

import { createJiti } from "jiti";

const GENERATED_NOTE =
  "<!-- Generated by `pnpm docs:gen` from aact's registries. Do not edit by hand. -->";

const ADR_BASE_URL = "https://github.com/Byndyusoft/aact/blob/main/";
const adrHelpUri = (adrPath: string): string =>
  ADR_BASE_URL + adrPath.split("/").map(encodeURIComponent).join("/");

const block = (parts: (string | null | undefined)[]): string =>
  parts
    .filter((p): p is string => typeof p === "string" && p.length > 0)
    .join("\n\n");

const page = (parts: (string | null | undefined)[]): string =>
  block(parts).trimEnd() + "\n";

// -----------------------------------------------------------------------------
// Rules
// -----------------------------------------------------------------------------

interface RuleExample {
  readonly label: "good" | "bad";
  readonly source: string;
  readonly note?: string;
}

interface RuleLike {
  readonly name: string;
  readonly description: string;
  readonly rationale?: string;
  readonly examples?: readonly RuleExample[];
  readonly adrPath?: string;
  readonly fix?: unknown;
}

const ruleHasFix = (rule: RuleLike): boolean => typeof rule.fix === "function";

const exampleBlock = (ex: RuleExample): string => {
  const head = ex.label === "good" ? "**✓ Good**" : "**✗ Bad**";
  const code = "```plantuml\n" + ex.source + "\n```";
  return ex.note ? `${head}\n\n${code}\n\n${ex.note}` : `${head}\n\n${code}`;
};

const rulePage = (rule: RuleLike): string => {
  const badges = [
    "`built-in`",
    ruleHasFix(rule) ? "🔧 auto-fix" : null,
    rule.adrPath ? `[ADR](${adrHelpUri(rule.adrPath)})` : null,
  ]
    .filter((b): b is string => b !== null)
    .join(" · ");

  return page([
    GENERATED_NOTE,
    `# \`${rule.name}\``,
    `> ${rule.description}`,
    badges,
    rule.rationale ? `## Why\n\n${rule.rationale}` : null,
    rule.examples && rule.examples.length > 0
      ? "## Examples\n\n" + rule.examples.map(exampleBlock).join("\n\n")
      : null,
    rule.adrPath
      ? `## Resources\n\n- [${rule.adrPath}](${adrHelpUri(rule.adrPath)})`
      : null,
  ]);
};

const rulesIndex = (rules: readonly RuleLike[]): string => {
  const rows = rules.map(
    (rule) =>
      `| [\`${rule.name}\`](./${rule.name}.md) | ${ruleHasFix(rule) ? "🔧" : ""} | ${rule.description} |`,
  );
  const table = [
    "| Rule | Fix | Description |",
    "| --- | :---: | --- |",
    ...rows,
  ].join("\n");
  return page([
    GENERATED_NOTE,
    "# Rules reference",
    "Built-in rules `aact check` runs. Each page below is generated from the\nrule's own metadata — description, rationale, and good/bad examples.",
    table,
  ]);
};

// -----------------------------------------------------------------------------
// Commands (from the citty command objects)
// -----------------------------------------------------------------------------

interface ArgDef {
  readonly type: string;
  readonly description?: string;
  readonly required?: boolean;
}

interface CommandLike {
  readonly meta?: { readonly name?: string; readonly description?: string };
  readonly args?: Record<string, ArgDef>;
  readonly subCommands?: Record<string, CommandLike>;
}

const argType = (def: ArgDef): string => {
  if (def.type === "positional") {
    return def.required ? "positional" : "positional, optional";
  }
  return def.required ? `${def.type}, required` : def.type;
};

const argsTable = (args: Record<string, ArgDef>): string | null => {
  const entries = Object.entries(args);
  if (entries.length === 0) return null;
  // Positionals first, then flags — stable within each group.
  const ordered = [...entries].sort(
    (a, b) =>
      (a[1].type === "positional" ? 0 : 1) -
      (b[1].type === "positional" ? 0 : 1),
  );
  const rows = ordered.map(([name, def]) => {
    const arg = def.type === "positional" ? `\`<${name}>\`` : `\`--${name}\``;
    return `| ${arg} | ${argType(def)} | ${def.description ?? ""} |`;
  });
  return [
    "| Argument | Type | Description |",
    "| --- | --- | --- |",
    ...rows,
  ].join("\n");
};

const commandSection = (
  fullName: string,
  cmd: CommandLike,
  level: number,
): string => {
  const subSections = cmd.subCommands
    ? Object.entries(cmd.subCommands).map(([sub, subCmd]) =>
        commandSection(`${fullName} ${sub}`, subCmd, level + 1),
      )
    : [];
  // A parent command's own args duplicate its subcommands' — document
  // the args on the subcommands, the parent just lists them.
  const ownArgs = cmd.args && !cmd.subCommands ? argsTable(cmd.args) : null;
  return block([
    `${"#".repeat(level)} \`aact ${fullName}\``,
    cmd.meta?.description ?? null,
    ownArgs,
    ...subSections,
  ]);
};

const commandsPage = (
  commands: readonly { name: string; cmd: CommandLike }[],
): string => {
  const overviewRows = commands.map(
    ({ name, cmd }) =>
      `| [\`aact ${name}\`](#aact-${name}) | ${cmd.meta?.description ?? ""} |`,
  );
  const overview = [
    "| Command | Description |",
    "| --- | --- |",
    ...overviewRows,
  ].join("\n");
  return page([
    GENERATED_NOTE,
    "# Commands",
    "Every command takes `--json` (and `--sarif` where shown) for machine output. Exit codes: `0` clean, `1` violations, `2` tool error.",
    overview,
    ...commands.map(({ name, cmd }) => commandSection(name, cmd, 2)),
  ]);
};

// -----------------------------------------------------------------------------
// Formats (from the format registry)
// -----------------------------------------------------------------------------

interface FormatRow {
  readonly name: string;
  readonly load: boolean;
  readonly generate: boolean;
  readonly fix: boolean;
  readonly pattern: string | readonly string[] | undefined;
}

const patternCell = (pattern: FormatRow["pattern"]): string => {
  if (pattern === undefined) return "—";
  const list = Array.isArray(pattern) ? pattern : [pattern];
  return list.map((p) => `\`${p}\``).join(", ");
};

const formatsPage = (formats: readonly FormatRow[]): string => {
  const rows = formats.map(
    (f) =>
      `| \`${f.name}\` | ${f.load ? "✓" : ""} | ${f.generate ? "✓" : ""} | ${f.fix ? "✓" : ""} | ${patternCell(f.pattern)} |`,
  );
  return page([
    GENERATED_NOTE,
    "# Formats",
    "Architecture sources aact can load, generate, and auto-fix. Pick one in `aact.config.ts` via `source` — the type is inferred from the path when omitted.",
    [
      "| Format | Load | Generate | Fix | Default pattern |",
      "| --- | :---: | :---: | :---: | --- |",
      ...rows,
    ].join("\n"),
  ]);
};

// -----------------------------------------------------------------------------
// Top-level reference index
// -----------------------------------------------------------------------------

const referenceIndex = (): string =>
  page([
    GENERATED_NOTE,
    "# Reference",
    "Generated from aact's own registries — do not edit by hand. Regenerate with `pnpm docs:gen`. For task-first walkthroughs see [the guides](../guides/).",
    [
      "- [Rules](./rules/) — built-in checks: rationale, examples, fix / ADR",
      "- [Commands](./commands.md) — CLI commands and flags",
      "- [Formats](./formats.md) — architecture source formats and capabilities",
    ].join("\n"),
  ]);

// -----------------------------------------------------------------------------
// Load registries + write
// -----------------------------------------------------------------------------

const repoRoot = path.resolve(import.meta.dirname, "..");
const refDir = path.join(repoRoot, "docs", "reference");
const rulesDir = path.join(refDir, "rules");

const jiti = createJiti(import.meta.url);

const { ruleRegistry } = await jiti.import<{
  ruleRegistry: readonly RuleLike[];
}>("../src/rules/registry");

// Order mirrors the subCommands block in src/cli/index.ts.
const commandSpecs: readonly [file: string, name: string][] = [
  ["init", "init"],
  ["check", "check"],
  ["analyze", "analyze"],
  ["model", "model"],
  ["diff/index", "diff"],
  ["view", "view"],
  ["generate", "generate"],
  ["rule", "rule"],
  ["skill", "skill"],
];
const commands = await Promise.all(
  commandSpecs.map(async ([file, name]) => {
    const mod = await jiti.import<Record<string, CommandLike>>(
      `../src/cli/commands/${file}`,
    );
    return { name, cmd: mod[name] };
  }),
);

const formatRegistry = await jiti.import<{
  knownFormatNames: () => readonly string[];
  loadFormat: (name: string) => Promise<{
    name: string;
    load?: unknown;
    generate?: unknown;
    fix?: unknown;
    defaultPattern?: string | readonly string[];
  }>;
}>("../src/formats/registry");
const formats: FormatRow[] = await Promise.all(
  formatRegistry.knownFormatNames().map(async (name) => {
    const f = await formatRegistry.loadFormat(name);
    return {
      name: f.name,
      load: typeof f.load === "function",
      generate: typeof f.generate === "function",
      fix: f.fix != null,
      pattern: f.defaultPattern,
    };
  }),
);

mkdirSync(rulesDir, { recursive: true });
// Drop stale rule pages so a removed rule doesn't leave an orphan file.
for (const file of readdirSync(rulesDir)) {
  if (file.endsWith(".md")) rmSync(path.join(rulesDir, file));
}

for (const rule of ruleRegistry) {
  writeFileSync(path.join(rulesDir, `${rule.name}.md`), rulePage(rule));
}
writeFileSync(path.join(rulesDir, "README.md"), rulesIndex(ruleRegistry));
writeFileSync(path.join(refDir, "commands.md"), commandsPage(commands));
writeFileSync(path.join(refDir, "formats.md"), formatsPage(formats));
writeFileSync(path.join(refDir, "README.md"), referenceIndex());

console.log(
  `Generated reference: ${ruleRegistry.length} rules, ${commands.length} commands, ${formats.length} formats in ${path.relative(repoRoot, refDir)}`,
);
