/**
 * Generate the per-rule reference pages from the rule registry.
 *
 * Run via `pnpm docs:gen`. CI verifies the checked-in pages are
 * up-to-date with `git diff --exit-code docs/reference/` after running
 * the generator (`pnpm docs:check`), so the reference can never drift
 * from the actual rule metadata (`description` / `rationale` /
 * `examples` / `adrPath` / `fix`).
 *
 * The generator owns the canonical formatting — `docs/reference/` is in
 * `.prettierignore` so prettier doesn't reflow it into a diff on every
 * `docs:check` run (same arrangement as `schemas/`).
 *
 * Runtime rule objects are loaded through jiti so this script can read
 * the live registry without a build step; type stripping handles the
 * script itself.
 */

import { mkdirSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import path from "node:path";

import { createJiti } from "jiti";

interface RuleExample {
  readonly label: "good" | "bad";
  readonly source: string;
  readonly note?: string;
}

interface RuleLike {
  readonly name: string;
  readonly description: string;
  readonly rationale?: string;
  readonly examples?: readonly RuleExample[];
  readonly adrPath?: string;
  readonly fix?: unknown;
}

const repoRoot = path.resolve(import.meta.dirname, "..");
const outDir = path.join(repoRoot, "docs", "reference", "rules");

// Mirror `aact rule explain`: anchor ADR links on the main branch so they
// survive renames and work from npm-installed builds without the local
// ADRs/ directory. Encode path segments individually so spaces survive.
const ADR_BASE_URL = "https://github.com/Byndyusoft/aact/blob/main/";
const adrHelpUri = (adrPath: string): string =>
  ADR_BASE_URL + adrPath.split("/").map(encodeURIComponent).join("/");

const GENERATED_NOTE =
  "<!-- Generated by `pnpm docs:gen` from the rule registry. Do not edit by hand. -->";

const hasFix = (rule: RuleLike): boolean => typeof rule.fix === "function";

const exampleBlock = (ex: RuleExample): string => {
  const head = ex.label === "good" ? "**✓ Good**" : "**✗ Bad**";
  const code = "```plantuml\n" + ex.source + "\n```";
  return ex.note ? `${head}\n\n${code}\n\n${ex.note}` : `${head}\n\n${code}`;
};

const examplesSection = (rule: RuleLike): string | null =>
  rule.examples && rule.examples.length > 0
    ? "## Examples\n\n" + rule.examples.map(exampleBlock).join("\n\n")
    : null;

const resourcesSection = (rule: RuleLike): string | null =>
  rule.adrPath
    ? `## Resources\n\n- [${rule.adrPath}](${adrHelpUri(rule.adrPath)})`
    : null;

const badgeLine = (rule: RuleLike): string =>
  [
    "`built-in`",
    hasFix(rule) ? "🔧 auto-fix" : null,
    rule.adrPath ? `[ADR](${adrHelpUri(rule.adrPath)})` : null,
  ]
    .filter((b): b is string => b !== null)
    .join(" · ");

const rulePage = (rule: RuleLike): string => {
  const blocks: (string | null)[] = [
    GENERATED_NOTE,
    `# \`${rule.name}\``,
    `> ${rule.description}`,
    badgeLine(rule),
    rule.rationale ? `## Why\n\n${rule.rationale}` : null,
    examplesSection(rule),
    resourcesSection(rule),
  ];
  return (
    blocks
      .filter((b): b is string => b !== null)
      .join("\n\n")
      .trimEnd() + "\n"
  );
};

const indexPage = (rules: readonly RuleLike[]): string => {
  const rows = rules.map(
    (rule) =>
      `| [\`${rule.name}\`](./${rule.name}.md) | ${hasFix(rule) ? "🔧" : ""} | ${rule.description} |`,
  );
  const table = [
    "| Rule | Fix | Description |",
    "| --- | :---: | --- |",
    ...rows,
  ].join("\n");
  return (
    [
      GENERATED_NOTE,
      "# Rules reference",
      "Built-in rules `aact check` runs. Each page below is generated from the\nrule's own metadata — description, rationale, and good/bad examples.",
      table,
    ].join("\n\n") + "\n"
  );
};

const jiti = createJiti(import.meta.url);
const { ruleRegistry } = await jiti.import<{
  ruleRegistry: readonly RuleLike[];
}>("../src/rules/registry");

mkdirSync(outDir, { recursive: true });
// Drop stale pages so a removed rule doesn't leave an orphan file.
for (const file of readdirSync(outDir)) {
  if (file.endsWith(".md")) rmSync(path.join(outDir, file));
}

for (const rule of ruleRegistry) {
  writeFileSync(path.join(outDir, `${rule.name}.md`), rulePage(rule));
}
writeFileSync(path.join(outDir, "README.md"), indexPage(ruleRegistry));

console.log(
  `Generated ${ruleRegistry.length} rule pages + index in ${path.relative(repoRoot, outDir)}`,
);
